# Generated by Django 4.2.1 on 2023-05-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Galería de productos', 'verbose_name_plural': 'Galería de productos'},
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_caracteristica', models.CharField(max_length=100)),
                ('producto', models.ManyToManyField(related_name='productos', to='store.product')),
            ],
            options={
                'verbose_name': 'Característica producto',
                'verbose_name_plural': 'Carecterísticas producto',
            },
        ),
    ]
